const cars = [
	{
		id: 1,
		name: 'new Mercedes-Benz L-Class L34 - 2001',
		img_url: 'url link to car1 image',
		owner_id: 1,
		owner_name: 'Chuksjoe O.',
		email: 'chuksjoe@live.com',
		created_on: Date(),
		year: 2001,
		state: 'used',
		status: 'available',
		price: 1500000.20,
		manufacturer: 'mercedes-benz',
		model: 'L-Class L34',
		body_type: 'coupe',
		fuel_type: 'petrol',
		mileage: 3400,
		color: 'yellow',
		transmission_type: 'automatic',
		description: 'other torie about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 2,
		name: 'new Mercedes-Benz L-Class L34 - 2001',
		img_url: 'url link to car2 image',
		owner_id: 1,
		owner_name: 'Chuksjoe O.',
		email: 'chuksjoe@live.com',
		created_on: Date(),
		year: 2001,
		state: 'new',
		status: 'sold',
		price: 3500000.20,
		manufacturer: 'mercedes-benz',
		model: 'L-Class L34',
		body_type: 'coupe',
		fuel_type: 'petrol',
		mileage: 3400,
		color: 'yellow',
		transmission_type: 'automatic',
		description: 'other torie about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 3,
		name: 'new Mercedes-Benz L-Class L34 - 2001',
		img_url: 'url link to car3 image',
		owner_id: 1,
		owner_name: 'Chuksjoe O.',
		email: 'chuksjoe@live.com',
		created_on: Date(),
		year: 1998,
		state: 'new',
		status: 'available',
		price: 14500000.20,
		manufacturer: 'mercedes-benz',
		model: 'L-Class L34',
		body_type: 'coupe',
		fuel_type: 'petrol',
		mileage: 3400,
		color: 'yellow',
		transmission_type: 'automatic',
		description: 'other torie about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
];

module.exports = cars;
