import util from '../util';

const url_prefix = 'https://res.cloudinary.com/chuks-automart/image/upload/v1559396268/uploads/car-';
const cars = [
	{
		id: 1,
		name: 'New 2015 Porsche 911',
		img_url: `${url_prefix}sample-1.jpg`,
		owner_id: 3,
		owner_name: 'Tolulope B.',
		email: 'tolu@live.com',
		created_on: util.getDate(),
		year: 2015,
		state: 'New',
		status: 'Available',
		price: 54396000.00,
		manufacturer: 'Porsche',
		model: '911',
		body_type: 'Coupe',
		fuel_type: 'petrol',
		doors: 4,
		fuel_cap: 58,
		mileage: 3400,
		color: 'gray',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 2,
		name: 'New 2019 Mercedes-Benz 1500 High Roof',
		img_url: `${url_prefix}sample-2.jpg`,
		owner_id: 2,
		owner_name: 'Emmanuel O.',
		email: 'emma@live.com',
		created_on: util.getDate(),
		year: 2019,
		state: 'New',
		status: 'Sold',
		price: 21168000.00,
		manufacturer: 'Mercedes-Benz',
		model: '1500 High Roof',
		body_type: 'Large Van',
		fuel_type: 'gas',
		doors: 4,
		fuel_cap: 58,
		mileage: 3400,
		color: 'dark gray',
		transmission_type: 'automatic',
		description: 'Looking to carry more passengers? The new Sprinter accomplishes that in a big way with totally new seating for up to 15 people, and provides an experience every one of them will enjoy. USB-C ports can keep them connected, and the spacious rear storage area provides ample room for luggage. All the while, you’ll know that they’re protected by a level of safety only Mercedes-Benz can deliver.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 3,
		name: 'New 2019 Toyota Sequoia SR5 RWD',
		img_url: `${url_prefix}sample-3.jpg`,
		owner_id: 3,
		owner_name: 'Tolulope B.',
		email: 'tolu@live.com',
		created_on: util.getDate(),
		year: 2019,
		state: 'New',
		status: 'Available',
		price: 18540000.00,
		manufacturer: 'Toyota',
		model: 'Sequoia SR5 RWD',
		body_type: 'Large SUV',
		fuel_type: 'petrol',
		doors: 4,
		fuel_cap: 58,
		mileage: 3400,
		color: 'white',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 4,
		name: 'Used 2017 Porsche 911 (991 II)',
		img_url: `${url_prefix}sample-4.jpg`,
		owner_id: 3,
		owner_name: 'Tolulope B.',
		email: 'tolu@live.com',
		created_on: util.getDate(),
		year: 2017,
		state: 'Used',
		status: 'Available',
		price: 35000000.00,
		manufacturer: 'Porsche',
		model: '911 (991 II)',
		body_type: 'Coupe',
		fuel_type: 'petrol',
		doors: 4,
		fuel_cap: 58,
		mileage: 3400,
		color: 'green',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 5,
		name: 'Used 2010 Ferrari 458 Italia',
		img_url: `${url_prefix}sample-5.jpg`,
		owner_id: 2,
		owner_name: 'Emmanuel O.',
		email: 'emma@live.com',
		created_on: util.getDate(),
		year: 2010,
		state: 'New',
		status: 'Available',
		price: 25000000.00,
		manufacturer: 'Ferrari',
		model: '458 Italia',
		body_type: 'Coupe',
		fuel_type: 'petrol',
		doors: 4,
		fuel_cap: 58,
		mileage: 3400,
		color: 'red, black',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 6,
		name: 'Used 2011 Mercedes-Benz SLS AMG',
		img_url: `${url_prefix}sample-6.jpg`,
		owner_id: 2,
		owner_name: 'Emmanuel O.',
		email: 'emma@live.com',
		created_on: util.getDate(),
		year: 2011,
		state: 'Used',
		status: 'Available',
		price: 25000000.00,
		manufacturer: 'Mercedes-Benz',
		model: 'SLS AMG',
		body_type: 'Convertible',
		fuel_type: 'gas',
		doors: 4,
		fuel_cap: 58,
		mileage: 4700,
		color: 'red',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 7,
		name: 'Used 1975 Chevrolet Bel Air',
		img_url: `${url_prefix}sample-7.jpg`,
		owner_id: 3,
		owner_name: 'Tolulope B.',
		email: 'tolu@live.com',
		created_on: util.getDate(),
		year: 1975,
		state: 'Used',
		status: 'Available',
		price: 10800000.00,
		manufacturer: 'Chevrolet',
		model: 'Bel Air',
		body_type: 'Coupe',
		fuel_type: 'petrol',
		doors: 4,
		fuel_cap: 58,
		mileage: 3400,
		color: 'red, white',
		transmission_type: 'manual',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 8,
		name: 'New 2019 BMW 430I',
		img_url: `${url_prefix}sample-8.jpg`,
		owner_id: 3,
		owner_name: 'Tolulope B.',
		email: 'tolu@live.com',
		created_on: util.getDate(),
		year: 2019,
		state: 'New',
		status: 'Available',
		price: 28000000.00,
		manufacturer: 'BMW',
		model: '430I',
		body_type: 'Coupe',
		fuel_type: 'petrol',
		doors: 4,
		fuel_cap: 58,
		mileage: 3400,
		color: 'white',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 9,
		name: 'Used 1989 Porsche 3.2 Carrera',
		img_url: `${url_prefix}sample-9.jpg`,
		owner_id: 2,
		owner_name: 'Emmanuel O.',
		email: 'emma@live.com',
		created_on: util.getDate(),
		year: 1989,
		state: 'Used',
		status: 'Available',
		price: 25000000.00,
		manufacturer: 'Porsche',
		model: '3.2 Carrera',
		body_type: 'Coupe',
		fuel_type: 'petrol',
		doors: 4,
		fuel_cap: 58,
		mileage: 8730,
		color: 'dark gray',
		transmission_type: 'automatic',
		description: 'This Porsche was sold new on June 9th1990 at Rusnak Porsche in Thousand Oaks, CA. The car was traded back into Rusnak and they placed a classified ad in the Los Angeles Times on September 13th, 1996. The 2ndowner saw this classified and raced down to purchase the car the very next day. He was a very obsessive collector and knew how special this car was. At this time the car had just 6,242 miles. He immediately placed the car in climate-controlled storage where the car was driven just 1,210 miles over the next 13 years.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 10,
		name: 'Used 1967 Cobra 5 WP',
		img_url: `${url_prefix}sample-10.jpg`,
		owner_id: 3,
		owner_name: 'Tolulope B.',
		email: 'tolu@live.com',
		created_on: util.getDate(),
		year: 1967,
		state: 'Used',
		status: 'Available',
		price: 14700000.00,
		manufacturer: 'Cobra',
		model: '5 WP',
		body_type: 'Convertible',
		fuel_type: 'petrol',
		doors: 4,
		fuel_cap: 58,
		mileage: 3400,
		color: 'blue, white',
		transmission_type: 'manual',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 11,
		name: 'New 2018 Chevrolet Camaro 2SS',
		img_url: `${url_prefix}sample-11.jpg`,
		owner_id: 3,
		owner_name: 'Tolulope B.',
		email: 'tolu@live.com',
		created_on: util.getDate(),
		year: 2011,
		state: 'New',
		status: 'Available',
		price: 40000000.00,
		manufacturer: 'Chevrolet',
		model: 'Camaro 2SS',
		body_type: 'Coupe',
		fuel_type: 'petrol',
		doors: 4,
		fuel_cap: 58,
		mileage: 3400,
		color: 'black',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 12,
		name: 'Used 2010 Volkswagen T600 VWW',
		img_url: `${url_prefix}sample-12.jpg`,
		owner_id: 3,
		owner_name: 'Tolulope B.',
		email: 'tolu@live.com',
		created_on: util.getDate(),
		year: 2010,
		state: 'Used',
		status: 'Available',
		price: 25000000.00,
		manufacturer: 'Volkswagen',
		model: 'T600 VWW',
		body_type: 'Large Van',
		fuel_type: 'petrol',
		doors: 4,
		fuel_cap: 58,
		mileage: 5200,
		color: 'cyan',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
];

module.exports = cars;
