const cars = [
	{
		id: 1,
		name: 'new Mercedes-Benz L-Class L34 - 2001',
		img_url: 'url link to car1 image',
		owner_id: 1,
		owner_name: 'Chuksjoe O.',
		email: 'chuksjoe@live.com',
		created_on: Date(),
		year: 2001,
		state: 'used',
		status: 'available',
		price: 1550000.20,
		manufacturer: 'mercedes-benz',
		model: 'L-Class L34',
		body_type: 'coupe',
		fuel_type: 'petrol',
		mileage: 3400,
		color: 'yellow',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 2,
		name: 'new Volkswagen Force 3 - 2001',
		img_url: 'url link to car2 image',
		owner_id: 1,
		owner_name: 'Chuksjoe O.',
		email: 'chuksjoe@live.com',
		created_on: Date(),
		year: 2001,
		state: 'new',
		status: 'sold',
		price: 3500000.20,
		manufacturer: 'volkswagen',
		model: 'force 3',
		body_type: 'small van',
		fuel_type: 'petrol',
		mileage: 3400,
		color: 'yellow',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 3,
		name: 'new Mercedes-Benz L-Class L34 - 2001',
		img_url: 'url link to car3 image',
		owner_id: 1,
		owner_name: 'Chuksjoe O.',
		email: 'chuksjoe@live.com',
		created_on: Date(),
		year: 1998,
		state: 'new',
		status: 'available',
		price: 14500000.20,
		manufacturer: 'mercedes-benz',
		model: 'L-Class L34',
		body_type: 'coupe',
		fuel_type: 'petrol',
		mileage: 3400,
		color: 'yellow',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 4,
		name: 'used Honda Accord - 1997',
		img_url: 'url link to car3 image',
		owner_id: 1,
		owner_name: 'Chuksjoe O.',
		email: 'chuksjoe@live.com',
		created_on: Date(),
		year: 1997,
		state: 'used',
		status: 'available',
		price: 3500000,
		manufacturer: 'honda',
		model: 'accord',
		body_type: 'coupe',
		fuel_type: 'petrol',
		mileage: 3400,
		color: 'yellow',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
	{
		id: 5,
		name: 'new Cadillac Dragon - 2011',
		img_url: 'url link to car3 image',
		owner_id: 1,
		owner_name: 'Chuksjoe O.',
		email: 'chuksjoe@live.com',
		created_on: Date(),
		year: 2011,
		state: 'new',
		status: 'available',
		price: 45000000,
		manufacturer: 'cadillac',
		model: 'dragon',
		body_type: 'convertible',
		fuel_type: 'petrol',
		mileage: 3400,
		color: 'yellow',
		transmission_type: 'automatic',
		description: 'other stories about the car goes here.',
		features: {
			ac: true,
			arm_rest: true,
			air_bag: true,
			dvd_player: false,
			fm_radio: true,
			tinted_windows: false,
		},
	},
];

module.exports = cars;
